### ISSUE TITLE
Alphabetical or Historical Ordering

### ISSUE THREAD

**Issue by mustafaozhan** [varabeis/SwiftUI#38]
Hello 👋  

Can you please order the `README.md` either alphabetically or historically, some canny people have been already merged their projects in first places.

**Comment by varabeis** [comment]
I am use historically order, but which project have invalid? I can change

**Comment by mustafaozhan** [comment]
@varabeis okay i went through all the PRs and those were the ones violated the order:

https://github.com/varabeis/SwiftUI/pull/1/files
https://github.com/varabeis/SwiftUI/pull/23/files
https://github.com/varabeis/SwiftUI/pull/30/files
https://github.com/varabeis/SwiftUI/pull/35/files

Not sure if there is direct push to master, if not then these are all :)

**Comment by varabeis** [comment]
Maybe you can render it and create PR ?

**Comment by mustafaozhan** [comment]
Sure will create PR at weekend 👍
